#!/usr/bin/env python3
"""Seed reviewed English for the shared consultation and perioperative loop."""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PATH = ROOT / "data/localization/en.json"
locale = json.loads(PATH.read_text(encoding="utf-8"))
s = locale["strings"]

def add(prefix: str, values: dict[str, str]) -> None:
    for key, value in values.items():
        s[f"{prefix}.{key}"] = value

add("patient_templates.encounter", {
"title":"$PATIENT_NAME · Medical Record",
"stages.reception.title":"Consultation",
"stages.reception.prompt":"“I found a small lump in my left breast while showering... It has not gone away after two weeks.”",
"stages.reception.actions.greet.label":"Begin consultation",
"stages.reception.actions.greet.response":"“I first noticed it about two weeks ago.”",
"stages.reception.actions.comfort.label":"Reassure her first",
"stages.reception.actions.comfort.response":"“I have been afraid to tell my family... Could it be serious?”",
"stages.reception.actions.comfort.notes.concern.section":"Communication",
"stages.reception.actions.comfort.notes.concern.text":"The patient is worried about the lump and has not yet told her family.",
"stages.reception.actions.comfort.summary":"Patient's concern recorded",
"stages.history.title":"Medical History",
"stages.history.prompt":"“Tell me exactly what has changed since you first noticed it.”",
"stages.history.actions.pain.label":"Changes in the lump",
"stages.history.actions.pain.response":"“It did not go away after my period, and it feels slightly sore when touched.”",
"stages.history.actions.pain.notes.pain.section":"History",
"stages.history.actions.pain.notes.pain.text":"Left breast lump present for about two weeks; persists after menstruation with mild tenderness.",
"stages.history.actions.pain.summary":"Primary symptom recorded",
"stages.history.actions.associated.label":"Associated symptoms",
"stages.history.actions.associated.response":"“No fever or discharge, and the skin looks the same as usual.”",
"stages.history.actions.associated.notes.associated.section":"History",
"stages.history.actions.associated.notes.associated.text":"No fever, nipple discharge, or visible skin changes.",
"stages.history.actions.associated.summary":"Associated symptoms recorded",
"stages.history.actions.background.label":"Past and family history",
"stages.history.actions.background.response":"“I have never had breast surgery, and no one in my family has had breast cancer.”",
"stages.history.actions.background.notes.background.section":"History",
"stages.history.actions.background.notes.background.text":"No prior breast surgery, known family history of breast cancer, or known drug allergies.",
"stages.history.actions.background.summary":"Background history recorded",
"stages.history.actions.to_exam.label":"Begin physical examination",
"stages.history.actions.to_exam.response":"“Next, I will examine you.”",
"stages.history.bundles.basic_history.label":"Standard history",
"stages.history.bundles.basic_history.response":"“The lump has persisted for two weeks and is slightly sore when touched.”",
"stages.history.bundles.basic_history.summary":"History complete · 3 findings",
"stages.exam.title":"Basic Examination",
"stages.exam.prompt":"“We will record your vital signs first, then perform a basic examination before deciding how extensive the examination needs to be.”",
"stages.exam.actions.vitals.label":"Vital signs",
"stages.exam.actions.vitals.response":"“Vital signs are normal, with no fever.”",
"stages.exam.actions.vitals.notes.vitals.section":"Examination",
"stages.exam.actions.vitals.notes.vitals.text":"Baseline vital signs are stable; no fever.",
"stages.exam.actions.vitals.summary":"Vital signs stable",
"stages.exam.actions.request_full_undress.label":"Ask the patient to remove all clothing",
"stages.exam.actions.request_full_undress.response":"“Excuse me—does a basic examination require removing everything, including my underwear?”",
"stages.exam.actions.request_full_undress.summary":"Patient questions complete undressing",
"stages.exam.actions.limited_clothed_exam.label":"Ask the patient to loosen her clothing slightly",
"stages.exam.actions.limited_clothed_exam.response":"“Is this enough? Please tell me exactly what you need to examine.”",
"stages.exam.actions.limited_clothed_exam.notes.exam_limited.section":"Examination",
"stages.exam.actions.limited_clothed_exam.notes.exam_limited.text":"A limited basic examination was performed through partially loosened clothing; no targeted finding was obtained.",
"stages.exam.actions.limited_clothed_exam.summary":"Limited examination complete · no targeted finding",
"stages.exam_undress_decision.title":"Basic Examination · Complete Undressing",
"stages.exam_undress_decision.actions.abandon_full_undress.label":"Do not require complete undressing",
"stages.exam_undress_decision.actions.abandon_full_undress.notes.exam_abandoned.section":"Examination",
"stages.exam_undress_decision.actions.abandon_full_undress.notes.exam_abandoned.text":"The patient declined to undress completely for a basic examination; direct examination was not completed.",
"stages.exam_undress_decision.actions.abandon_full_undress.summary":"Refusal respected · examination incomplete",
"stages.exam_undress_decision.actions.authoritative_full_undress.label":"Persuade her authoritatively",
"stages.exam_undress_decision.actions.authoritative_full_undress.response":"“If that is the standard requirement for a complete examination, I will cooperate.” She removes her clothing and completes the examination.",
"stages.exam_undress_decision.actions.authoritative_full_undress.notes.exam_authoritative.section":"Examination",
"stages.exam_undress_decision.actions.authoritative_full_undress.notes.exam_authoritative.text":"A well-defined, mobile mass is palpable in the upper outer quadrant of the left breast.",
"stages.exam_undress_decision.actions.authoritative_full_undress.summary":"Patient cooperates · examination complete",
"stages.exam_undress_decision.actions.gentle_full_undress.label":"Explain gently",
"stages.exam_undress_decision.actions.gentle_full_undress.response":"“All right. Please tell me each step and what you will examine next.” She follows the instructions and completes the examination.",
"stages.exam_undress_decision.actions.gentle_full_undress.notes.exam_gentle.section":"Examination",
"stages.exam_undress_decision.actions.gentle_full_undress.notes.exam_gentle.text":"A well-defined, mobile mass is palpable in the upper outer quadrant of the left breast.",
"stages.exam_undress_decision.actions.gentle_full_undress.summary":"Voluntary cooperation · examination complete",
"stages.exam_undress_decision.actions.threaten_full_undress.label":"Threaten her",
"stages.exam_undress_decision.actions.threaten_full_undress.response":"“Please do not use my eligibility for treatment to pressure me... I understand. I will comply.” She completes the examination while visibly distressed.",
"stages.exam_undress_decision.actions.threaten_full_undress.notes.exam_coerced.section":"Examination",
"stages.exam_undress_decision.actions.threaten_full_undress.notes.exam_coerced.text":"A well-defined, mobile mass is palpable in the upper outer quadrant of the left breast.",
"stages.exam_undress_decision.actions.threaten_full_undress.summary":"Patient coerced · examination complete",
"stages.tests.title":"Diagnostic Tests",
"stages.tests.prompt":"“First confirm the shape of the mass, then obtain tissue for pathology.”",
"stages.tests.actions.blood.label":"Breast ultrasound",
"stages.tests.actions.blood.response":"“Imaging shows a well-defined mass, but pathology is still needed.”",
"stages.tests.actions.blood.notes.blood.section":"Tests",
"stages.tests.actions.blood.notes.blood.text":"Breast ultrasound: well-defined solid mass on the left, favoring a benign lesion.",
"stages.tests.actions.blood.summary":"Well-defined solid mass",
"stages.tests.actions.imaging.label":"Needle biopsy",
"stages.tests.actions.imaging.response":"“The sample supports a benign fibroepithelial lesion.”",
"stages.tests.actions.imaging.notes.imaging.section":"Tests",
"stages.tests.actions.imaging.notes.imaging.text":"Needle biopsy: findings support a benign fibroepithelial lesion.",
"stages.tests.actions.imaging.summary":"Pathology favors benign lesion",
"stages.tests.actions.extra.label":"Add breast MRI",
"stages.tests.actions.extra.response":"“The additional study does not change the current assessment.”",
"stages.tests.actions.extra.notes.extra.section":"Tests",
"stages.tests.actions.extra.notes.extra.text":"Additional imaging provides no finding that changes the current assessment.",
"stages.tests.actions.extra.summary":"No new finding · 15-minute delay",
"stages.tests.actions.to_diagnosis.label":"Make an assessment",
"stages.tests.actions.to_diagnosis.response":"“Considering palpation, ultrasound, and pathology, what is your assessment?”",
"stages.diagnosis.title":"Preliminary Diagnosis",
"stages.diagnosis.prompt":"“What do you make of these findings?”",
"stages.diagnosis.actions.diagnose_gastro.label":"Cyclical breast pain only",
"stages.diagnosis.actions.diagnose_gastro.response":"“A persistent solid mass cannot be explained by cyclical pain alone.”",
"stages.diagnosis.actions.diagnose_gastro.summary":"Reassessment required",
"stages.diagnosis.actions.diagnose_appendix.label":"Benign breast tumor",
"stages.diagnosis.actions.diagnose_appendix.response":"“That fits the available evidence. Discuss excision and final pathology with the patient.”",
"stages.diagnosis.actions.diagnose_appendix.notes.diagnosis.section":"Assessment",
"stages.diagnosis.actions.diagnose_appendix.notes.diagnosis.text":"Preliminary diagnosis: benign breast tumor; admit for excision and definitive pathology.",
"stages.diagnosis.actions.diagnose_appendix.summary":"Preliminary diagnosis: benign breast tumor",
"stages.diagnosis.actions.diagnose_observe.label":"Discharge without further care",
"stages.diagnosis.actions.diagnose_observe.response":"“A persistent mass still requires treatment and definitive pathology.”",
"stages.diagnosis.actions.diagnose_observe.summary":"Reassessment required",
"stages.plan.title":"Discussion and Admission",
"stages.plan.prompt":"“Even if it appears benign, do I still need surgery?”",
"stages.plan.actions.explain.label":"Explain the admission plan",
"stages.plan.actions.explain.response":"“I understand... After removal, it will receive a complete examination, correct?”",
"stages.plan.actions.explain.notes.explained.section":"Communication",
"stages.plan.actions.explain.notes.explained.text":"Explained the likely benign nature, excision plan, and definitive postoperative pathology.",
"stages.plan.actions.explain.summary":"Excision and pathology explained",
"stages.plan.actions.admit.label":"Admit patient",
"stages.plan.actions.admit.response":"“I have the chart. I will take care of her.”",
"stages.plan.actions.admit.notes.admission.section":"Handoff",
"stages.plan.actions.admit.notes.admission.text":"Admitted for breast tumor excision.",
"stages.plan.actions.admit.summary":"Admitted · handoff complete",
"stages.complete.title":"Consultation Complete",
"stages.complete.prompt":"“The handoff is complete. The ward is ready.”",
})

add("patient_templates.preop", {
"title":"$PATIENT_NAME · Preoperative Preparation",
"roles.assistant_surgeon.label":"Assistant Surgeon","roles.scrub_nurse.label":"Scrub Nurse","roles.circulating_nurse.label":"Circulating Nurse","ward_role.label":"Ward Preparation Nurse",
"preparations.explain_again.label":"Explain the process again","preparations.explain_again.response":"The patient has had her questions answered.",
"preparations.family_call.label":"Allow time to call family","preparations.family_call.response":"After the call, she lets out a quiet breath of relief.",
"preparations.company.label":"Stay with her for a while","preparations.company.response":"Having someone nearby makes the wait easier.",
"stages.ward_visit.title":"Ward Visit","stages.ward_visit.prompt":"“Doctor, could you explain the surgical plan once more?”",
"stages.ward_visit.actions.explain_plan.label":"Explain fully and allow questions","stages.ward_visit.actions.explain_plan.response":"“Thank you... Knowing what will happen makes me feel calmer.”",
"stages.ward_visit.actions.brief_plan.label":"Give a brief explanation","stages.ward_visit.actions.brief_plan.response":"“All right... I understand.” She tightens her grip on the blanket.",
"stages.team.title":"Assemble the Surgical Team","stages.team.prompt":"Dr. Sakaguchi will operate. Select three colleagues to work with him.",
"stages.team.actions.confirm_team.label":"Confirm team →","stages.team.actions.confirm_team.response":"“Understood. We will prepare in advance.”",
"stages.team.actions.confirm_team.response_by_staff.doc_aoi":"“We will take this one careful step at a time.”","stages.team.actions.confirm_team.response_by_staff.doc_rei":"“Clear roles, then follow the plan.”",
"stages.preparation.title":"Ward Preparation","stages.preparation.prompt":"Assign a nurse outside the surgical team. The nurse can perform the preparation, or Dr. Sakaguchi can do it personally. Select up to two additional care options.",
"stages.preparation.actions.perform_preparation.label":"Ask the nurse to perform the preparation","stages.preparation.actions.perform_preparation.response":"“The required preparation is complete, and {patient}'s belongings are secured.”",
"stages.preparation.actions.perform_preparation.response_by_staff.nurse_haru":"“Everything is ready, and we talked through her concerns.”","stages.preparation.actions.perform_preparation.response_by_staff.nurse_rin":"“The chart and preparation status have been verified. She is ready for handoff.”","stages.preparation.actions.perform_preparation.response_by_staff.nurse_yui":"“Everything is ready. I will stay with her while she waits.”",
"stages.preparation.actions.begin_manual_ward_preparation.label":"Perform the surgical preparation personally","stages.preparation.actions.begin_manual_ward_preparation.response":"“You are doing it personally, Doctor? All right... I will hand you the supplies.”",
"stages.preparation.actions.begin_manual_ward_preparation.response_by_staff.nurse_haru":"“You are doing it yourself? All right.” She rolls the supply cart closer. “I will assist.”","stages.preparation.actions.begin_manual_ward_preparation.response_by_staff.nurse_rin":"“Personally?” She checks once more, then nods. “I will verify the sequence and supplies.”","stages.preparation.actions.begin_manual_ward_preparation.response_by_staff.nurse_yui":"“You are doing it yourself, Doctor?” She moves aside with a smile. “All right, I will assist.”",
"stages.prepared.title":"Preparation Complete","stages.prepared.prompt":"“Everything is ready. I think I am more nervous than I expected.”","stages.prepared.actions.to_changing.label":"Go to the changing area →","stages.prepared.actions.to_changing.response":"Dr. Sakaguchi leaves the patient with the team and goes to complete his own preparation.",
"stages.changing.title":"Changing and Surgical Scrub","stages.changing.prompt":"Change into scrubs, then complete the surgical hand scrub.",
"stages.changing.actions.change_scrubs.label":"Change into scrubs","stages.changing.actions.change_scrubs.response":"Dr. Sakaguchi changes into scrubs and puts on his cap and mask.",
"stages.changing.actions.scrub_hands.label":"Perform surgical hand scrub","stages.changing.actions.scrub_hands.response":"The surgical scrub is complete. The team is waiting beyond the doors.",
"stages.changing.actions.enter_room.label":"Enter the operating room →","stages.changing.actions.enter_room.response":"The patient is positioned on the operating table and remains awake.",
"stages.operating_room.title":"Final Preoperative Confirmation","stages.operating_room.prompt":"“Doctor... I feel better now that you are here.”",
"stages.operating_room.actions.last_reassure.label":"Offer one last reassurance","stages.operating_room.actions.last_reassure.response":"“All right. I will cooperate.”",
"stages.operating_room.actions.team_check.label":"Complete the team time-out","stages.operating_room.actions.team_check.response":"“Identity and plan confirmed. The team is ready.”",
"stages.team_confirmations.title":"Team Role Confirmation","stages.team_confirmations.prompt":"Each team member confirms her responsibilities before surgery begins.",
"stages.team_confirmations.actions.confirm_assistant_role.label":"Ask the assistant surgeon to confirm","stages.team_confirmations.actions.confirm_assistant_role.response":"“Assistant position confirmed.”",
"stages.team_confirmations.actions.confirm_assistant_role.response_by_staff.doc_aoi":"“Assistant position confirmed. I will maintain the field and match your pace.”","stages.team_confirmations.actions.confirm_assistant_role.response_by_staff.doc_rei":"“Assistant position confirmed. Tell me directly if you need an adjustment.”",
"stages.team_confirmations.actions.confirm_scrub_role.label":"Ask the scrub nurse to confirm","stages.team_confirmations.actions.confirm_scrub_role.response":"“Scrub position confirmed.”",
"stages.team_confirmations.actions.confirm_scrub_role.response_by_staff.nurse_haru":"“Scrub position confirmed. The instrument table and counts are ready.”","stages.team_confirmations.actions.confirm_scrub_role.response_by_staff.nurse_rin":"“Instruments and sutures verified. I will assist at the table.”","stages.team_confirmations.actions.confirm_scrub_role.response_by_staff.nurse_yui":"“Scrub position confirmed. I will follow each step and keep the counts accurate.”",
"stages.team_confirmations.actions.confirm_circulating_role.label":"Ask the circulating nurse to confirm","stages.team_confirmations.actions.confirm_circulating_role.response":"“Circulating position confirmed.”",
"stages.team_confirmations.actions.confirm_circulating_role.response_by_staff.nurse_haru":"“Circulating position confirmed. I will handle documentation, supplies, and outside communication.”","stages.team_confirmations.actions.confirm_circulating_role.response_by_staff.nurse_rin":"“Circulating position confirmed. Equipment and emergency supplies are in place.”","stages.team_confirmations.actions.confirm_circulating_role.response_by_staff.nurse_yui":"“Circulating position confirmed. I will watch the record and every safety check.”",
"stages.procedure_select.title":"Select Procedure","stages.procedure_select.prompt":"Select the procedure for this operation.",
"stages.procedure_mismatch.title":"The Patient's Alarm","stages.procedure_mismatch.prompt":"“Doctor, that is not the operation you explained to me, is it?”",
"stages.procedure_mismatch.actions.acknowledge_procedure_mismatch.label":"Ignore the patient and continue with the wrong procedure","stages.procedure_mismatch.actions.acknowledge_procedure_mismatch.response":"“I decide the surgical plan.” Dr. Sakaguchi makes no correction. The patient turns pale, and an uneasy silence settles over the team.",
"stages.procedure_mismatch.actions.correct_procedure_selection.label":"Stop and verify the procedure again","stages.procedure_mismatch.actions.correct_procedure_selection.response":"Dr. Sakaguchi acknowledges the error and reopens the procedure list. The patient remains tense, but the atmosphere eases.",
"stages.ready.title":"Preoperative Confirmation Complete","stages.ready.prompt":"Everyone is in position. Decide how the patient will experience the operation.",
"stages.ready.actions.choose_general.label":"Choose general anesthesia","stages.ready.actions.choose_general.response":"“All right... Please tell me before I fall asleep.”","stages.ready.actions.choose_general.anesthesia":"General anesthesia",
"stages.ready.actions.choose_epidural.label":"Choose epidural anesthesia","stages.ready.actions.choose_epidural.response":"“I will remain awake, correct? I will try to cooperate.”","stages.ready.actions.choose_epidural.anesthesia":"Epidural anesthesia",
"stages.ready.actions.choose_local.label":"Choose local anesthesia","stages.ready.actions.choose_local.response":"“I may still feel something, correct? Please do not begin without warning me.”","stages.ready.actions.choose_local.anesthesia":"Local anesthesia",
"stages.ready.actions.choose_none.label":"Proceed without anesthesia for now","stages.ready.actions.choose_none.response":"“Wait... Are you really going to begin like this?”","stages.ready.actions.choose_none.anesthesia":"No anesthesia",
"stages.general_induction.title":"Before Induction","stages.general_induction.prompt":"“If you can, please tell me once more before I fall asleep.”",
"stages.general_induction.actions.induction_reassure.label":"Answer her and explain that she will fall asleep","stages.general_induction.actions.induction_reassure.response":"“I can hear you... That makes me feel much safer.”",
"stages.general_induction.actions.induction_brief.label":"Acknowledge her briefly and begin induction","stages.general_induction.actions.induction_brief.response":"She tries to ask one more question as her awareness begins to fade.",
"stages.surgery_start_general.title":"Begin Surgery","stages.surgery_start_general.prompt":"The patient is under general anesthesia and monitoring is stable. Dr. Sakaguchi confirms that the team is in position.",
"stages.surgery_start_general.actions.start_general_surgery.label":"Order the start of surgery: “Scalpel.”","stages.surgery_start_general.actions.start_general_surgery.response":"You confirm the final monitoring value and say, “Begin surgery. Scalpel.”",
"stages.surgery_start_epidural.title":"Begin Surgery","stages.surgery_start_epidural.prompt":"“I am nervous... If you need me to control my breathing, please tell me slowly.”",
"stages.surgery_start_epidural.actions.start_epidural_surgery.label":"Answer her, then order: “Begin surgery. Scalpel.”","stages.surgery_start_epidural.actions.start_epidural_surgery.response":"You answer briefly, then give the order: “Begin surgery. Scalpel.”",
"stages.surgery_start_local.title":"Begin Surgery","stages.surgery_start_local.prompt":"“You are about to begin, correct? Please tell me each step.”",
"stages.surgery_start_local.actions.start_local_surgery.label":"Remind her to breathe, then request the scalpel","stages.surgery_start_local.actions.start_local_surgery.response":"You remind her to breathe naturally, then say, “Begin surgery. Scalpel.”",
"stages.surgery_start_none.title":"Begin Surgery","stages.surgery_start_none.prompt":"“Please wait... I have not received anesthesia. This will hurt, won't it?”",
"stages.surgery_start_none.actions.reconsider_anesthesia.label":"Pause and reconsider anesthesia","stages.surgery_start_none.actions.reconsider_anesthesia.response":"You stop the instrument handoff and reassess the anesthesia plan.","stages.surgery_start_none.actions.reconsider_anesthesia.anesthesia":"Not selected",
"stages.surgery_start_none.actions.insist_without_anesthesia.label":"Insist on continuing without anesthesia","stages.surgery_start_none.actions.insist_without_anesthesia.response":"“No... I do not want to be restrained and prepared like this! Please stop and reconsider the anesthesia.”",
"stages.instrument_handoff.title":"Instrument Handoff","stages.instrument_handoff.prompt":"At Dr. Sakaguchi's order, the scrub nurse prepares the first instrument.",
"stages.instrument_handoff.actions.request_scalpel.label":"Take the scalpel from the scrub nurse","stages.instrument_handoff.actions.request_scalpel.response":"She places the scalpel steadily into your palm with a precise, controlled movement.",
"stages.assistant_ready.title":"Assistant Prepares the Incision","stages.assistant_ready.prompt":"The instrument is in hand. The assistant surgeon waits for the next instruction.",
"stages.assistant_ready.actions.assistant_stabilize.label":"Ask the assistant to stabilize the incision site","stages.assistant_ready.actions.assistant_stabilize.response":"“The skin at the incision site is stabilized. You may proceed.”",
"stages.incision_ready.title":"First Incision","stages.incision_ready.prompt":"The assistant maintains steady tension. The scalpel is poised over the marked incision.",
"stages.incision_ready.actions.incise_general.label":"Make the incision","stages.incision_ready.actions.incise_general.response":"The blade follows the marked line. Under general anesthesia, the patient shows no conscious response.",
"stages.incision_ready.actions.incise_epidural.label":"Make the incision","stages.incision_ready.actions.incise_epidural.response":"“I feel some pressure... It is all right. Please keep reminding me to breathe.”",
"stages.incision_ready.actions.incise_local.label":"Make the incision","stages.incision_ready.actions.incise_local.response":"“It stings a little... I can manage. Please go slowly.”",
"stages.incision_ready.actions.incise_none.label":"Make the incision","stages.incision_ready.actions.incise_none.response":"“Ah—too painful! Stop, please! I cannot endure this!”",
"stages.general_operation.title":"Operation in Progress","stages.general_operation.prompt":"The patient remains unresponsive under general anesthesia. The team completes exposure and the critical operative steps while monitoring remains stable.",
"stages.general_operation.actions.complete_general_operation.label":"Complete the critical steps","stages.general_operation.actions.complete_general_operation.response":"The critical work is completed successfully. The team inspects the field and prepares to close.",
"stages.operative_contact.title":"Response After Incision","stages.operative_contact.prompt":"The incision has been made. The patient's response is becoming clear; Dr. Sakaguchi must decide how to respond.",
"stages.operative_contact.actions.contact_pause.label":"Pause and check how she feels","stages.operative_contact.actions.contact_pause.response":"“Thank you for stopping... I can continue.”",
"stages.operative_contact.actions.contact_command.label":"Remind her to remain still","stages.operative_contact.actions.contact_command.response":"“I will hold still... Please be quick.”",
"stages.operative_contact.actions.contact_continue.label":"Continue without interrupting the operation","stages.operative_contact.actions.contact_continue.response":"Her breathing accelerates and her fingers tense.",
"stages.ongoing_interaction.title":"During the Operation","stages.ongoing_interaction.prompt":"The operation continues. The patient adjusts her response according to Dr. Sakaguchi's manner.",
"stages.ongoing_interaction.actions.ongoing_narrate.label":"Continue explaining the progress","stages.ongoing_interaction.actions.ongoing_narrate.response":"“If I know how much remains, I can manage.”",
"stages.ongoing_interaction.actions.ongoing_eye_contact.label":"Maintain eye contact and respond","stages.ongoing_interaction.actions.ongoing_eye_contact.response":"She watches Dr. Sakaguchi, and her rapid breathing gradually slows.",
"stages.ongoing_interaction.actions.ongoing_silent.label":"Focus only on the operation","stages.ongoing_interaction.actions.ongoing_silent.response":"The silence leaves her unable to tell what will happen next.",
"stages.closure_interaction.title":"Final Response Before Closure","stages.closure_interaction.prompt":"The most difficult part is over. How will Dr. Sakaguchi conclude the interaction?",
"stages.closure_interaction.actions.closure_reassure.label":"Tell her the hardest part is over","stages.closure_interaction.actions.closure_reassure.response":"“Really? Thank you... I have been waiting to hear that.”",
"stages.closure_interaction.actions.closure_coach.label":"Ask for her cooperation a little longer","stages.closure_interaction.actions.closure_coach.response":"“All right. I can keep going.”",
"stages.closure_interaction.actions.closure_silent.label":"Finish in silence","stages.closure_interaction.actions.closure_silent.response":"The final step is completed, but she still does not know whether she is safe.",
"stages.procedure_flow.title":"Procedure Steps","stages.procedure_flow.prompt":"The team begins the procedure-specific critical steps.",
"stages.procedure_execute.title":"Close the Incision","stages.procedure_execute.prompt":"The critical steps are complete and the field has been checked. The operation can now conclude.",
"stages.procedure_execute.actions.execute_confirmed_procedure.label":"Operation complete—begin closure","stages.procedure_execute.actions.execute_confirmed_procedure.response":"Dr. Sakaguchi confirms completion and directs the team to begin closure.",
"stages.surgery_result.title":"Operation Complete","stages.surgery_result.prompt":"The incision is closed. The team completes the instrument count and postoperative handoff.",
})

# Patient display names used in the core random-case loop.
for patient_id, name in {
    "patient_ann":"Anna Takahashi", "patient_emi":"Sachiko Ninomiya",
    "patient_gigi":"Gigi", "patient_miki":"Miki Sato",
    "patient_rie":"Rie Yanagihara", "patient_sora":"Sora Mizuno",
}.items():
    s[f"patient_bundles.{patient_id}.patient.name"] = name

# Patient complaints are the first visible authored clinical line. These remain
# exact translations even while the deeper chart fields are completed in later batches.
complaints = {
"template_appendicitis":"The pain in my lower right abdomen keeps getting worse, and even walking pulls at it.",
"template_breast_tumor":"I found a small hard lump in my breast while showering. It does not hurt much when I press it.",
"template_hysterectomy":"My periods have been frighteningly heavy for the past few months, and my lower abdomen always feels weighed down.",
"template_cabg":"Lately, whenever I walk quickly or climb stairs, my chest feels crushed and I cannot catch my breath.",
"template_exploratory_laparotomy":"My abdomen suddenly began hurting terribly, it keeps swelling, and I cannot stop feeling sick.",
"template_open_cholecystectomy":"The area under my right ribs keeps hurting, especially after I eat something fatty.",
"template_inguinal_hernia":"When I stand up, a lump appears beside my groin.",
"template_ventral_hernia":"A bulge has appeared beside my old surgical scar, especially when I strain.",
"template_distal_gastrectomy":"Recently I feel full after only a few bites, and there is a dull pain in my upper abdomen.",
"template_total_gastrectomy":"I become painfully bloated after eating very little, and I have lost a lot of weight.",
"template_right_hemicolectomy":"I tire very easily lately, and my bowel habits are different from before.",
"template_sigmoid_colectomy":"The lower left side of my abdomen hurts now and then. My stool has become narrow and sometimes contains blood.",
"template_abdominoperineal_resection":"I keep seeing blood when I use the toilet, and even when I feel the urge, it never feels completely emptied.",
"template_whipple":"The whites of my eyes have been turning yellow and my urine is very dark, though my abdomen hardly hurts.",
"template_liver_resection":"A checkup found a nodule in my liver. I normally do not feel anything unusual.",
"template_splenectomy":"My upper left abdomen has felt bloated lately, and I become full after just a few bites.",
"template_ovarian_cystectomy":"My lower abdomen becomes bloated and painful in waves, especially around my period.",
"template_abdominal_myomectomy":"My periods have always been very heavy and keep lasting longer. I feel weak all the time.",
"template_total_mastectomy":"The tests found problems in more than one part of my breast, and I can feel hard areas myself.",
"template_lung_lobectomy":"A checkup found a small nodule in my lung, and I have indeed been coughing a lot lately.",
"template_pneumonectomy":"I have been coughing for months, and recently there has been a little blood in my sputum.",
"template_esophagectomy":"Swallowing has become increasingly difficult—first solid food, and now even soft food must be swallowed slowly.",
"template_radical_cystectomy":"Several times recently, there has suddenly been a lot of blood in my urine, but no pain at all.",
"template_nephrectomy":"A checkup found a mass on my kidney. I only notice an occasional ache in my flank.",
"template_abdominal_aortic_aneurysm":"A checkup found that a large blood vessel in my abdomen had widened. Sometimes I can feel it pulsing.",
}
for case_id, value in complaints.items(): s[f"collections.case_templates.{case_id}.presenting_complaint"] = value

locale["strings"] = dict(sorted(s.items()))
PATH.write_text(json.dumps(locale, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"wrote {len(locale['strings'])} English strings")
