extends SceneTree

const App = preload("res://godot/ui/app.gd")
const PreopView = preload("res://godot/ui/preop_view.gd")
var checks := 0
var failures := 0

class MockPreparation extends RefCounted:
	var flags: Array[String] = []

func expect(condition: bool, message: String) -> void:
	checks += 1
	if not condition:
		failures += 1
		push_error(message)

func _initialize() -> void:
	call_deferred("run")

func run() -> void:
	var app := App.new()
	root.add_child(app)
	await process_frame
	expect(app.content.errors.is_empty(), "Content failed to load before the video smoke test")
	expect(ResourceLoader.exists(app.ABDOMINAL_INCISION_VIDEO), "Abdominal incision OGV is missing")
	expect(load(app.ABDOMINAL_INCISION_VIDEO) is VideoStream, "Abdominal incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.ABDOMINAL_INCISION_VIDEO_V2), "Second abdominal incision OGV is missing")
	expect(load(app.ABDOMINAL_INCISION_VIDEO_V2) is VideoStream, "Second abdominal incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.ABDOMINAL_INCISION_VIDEO_V3), "Third abdominal incision OGV is missing")
	expect(load(app.ABDOMINAL_INCISION_VIDEO_V3) is VideoStream, "Third abdominal incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.ABDOMINAL_INCISION_VIDEO_V4), "Fourth abdominal incision OGV is missing")
	expect(load(app.ABDOMINAL_INCISION_VIDEO_V4) is VideoStream, "Fourth abdominal incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.ABDOMINAL_INCISION_VIDEO_V5), "Fifth abdominal incision OGV is missing")
	expect(load(app.ABDOMINAL_INCISION_VIDEO_V5) is VideoStream, "Fifth abdominal incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.ABDOMINAL_INCISION_VIDEO_V6), "Sixth abdominal incision OGV is missing")
	expect(load(app.ABDOMINAL_INCISION_VIDEO_V6) is VideoStream, "Sixth abdominal incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.ABDOMINAL_INCISION_VIDEO_V7), "Seventh abdominal incision OGV is missing")
	expect(load(app.ABDOMINAL_INCISION_VIDEO_V7) is VideoStream, "Seventh abdominal incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.BREAST_INCISION_VIDEO), "Breast incision OGV is missing")
	expect(load(app.BREAST_INCISION_VIDEO) is VideoStream, "Breast incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.BREAST_INCISION_VIDEO_V2), "Second breast incision OGV is missing")
	expect(load(app.BREAST_INCISION_VIDEO_V2) is VideoStream, "Second breast incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.BREAST_INCISION_VIDEO_V3), "Third breast incision OGV is missing")
	expect(load(app.BREAST_INCISION_VIDEO_V3) is VideoStream, "Third breast incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.BREAST_INCISION_VIDEO_V4), "Fourth breast incision OGV is missing")
	expect(load(app.BREAST_INCISION_VIDEO_V4) is VideoStream, "Fourth breast incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.BREAST_INCISION_VIDEO_V5), "Fifth breast incision OGV is missing")
	expect(load(app.BREAST_INCISION_VIDEO_V5) is VideoStream, "Fifth breast incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.BREAST_INCISION_VIDEO_V6), "Sixth breast incision OGV is missing")
	expect(load(app.BREAST_INCISION_VIDEO_V6) is VideoStream, "Sixth breast incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.BREAST_INCISION_VIDEO_V7), "Seventh breast incision OGV is missing")
	expect(load(app.BREAST_INCISION_VIDEO_V7) is VideoStream, "Seventh breast incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.BREAST_INCISION_VIDEO_V8), "Eighth breast incision OGV is missing")
	expect(load(app.BREAST_INCISION_VIDEO_V8) is VideoStream, "Eighth breast incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.PELVIC_INCISION_VIDEO), "Pelvic incision OGV is missing")
	expect(load(app.PELVIC_INCISION_VIDEO) is VideoStream, "Pelvic incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.PELVIC_INCISION_VIDEO_V2), "Second pelvic incision OGV is missing")
	expect(load(app.PELVIC_INCISION_VIDEO_V2) is VideoStream, "Second pelvic incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.PELVIC_INCISION_VIDEO_V3), "Third pelvic incision OGV is missing")
	expect(load(app.PELVIC_INCISION_VIDEO_V3) is VideoStream, "Third pelvic incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.PELVIC_INCISION_VIDEO_V4), "Fourth pelvic incision OGV is missing")
	expect(load(app.PELVIC_INCISION_VIDEO_V4) is VideoStream, "Fourth pelvic incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.THORACIC_INCISION_VIDEO), "Thoracic incision OGV is missing")
	expect(load(app.THORACIC_INCISION_VIDEO) is VideoStream, "Thoracic incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.THORACIC_INCISION_VIDEO_V2), "Second thoracic incision OGV is missing")
	expect(load(app.THORACIC_INCISION_VIDEO_V2) is VideoStream, "Second thoracic incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.THORACIC_INCISION_VIDEO_V3), "Third thoracic incision OGV is missing")
	expect(load(app.THORACIC_INCISION_VIDEO_V3) is VideoStream, "Third thoracic incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.THORACIC_INCISION_VIDEO_V4), "Fourth thoracic incision OGV is missing")
	expect(load(app.THORACIC_INCISION_VIDEO_V4) is VideoStream, "Fourth thoracic incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.THORACIC_INCISION_VIDEO_V5), "Fifth thoracic incision OGV is missing")
	expect(load(app.THORACIC_INCISION_VIDEO_V5) is VideoStream, "Fifth thoracic incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.THORACIC_INCISION_VIDEO_V6), "Sixth thoracic incision OGV is missing")
	expect(load(app.THORACIC_INCISION_VIDEO_V6) is VideoStream, "Sixth thoracic incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.THORACIC_INCISION_VIDEO_V7), "Seventh thoracic incision OGV is missing")
	expect(load(app.THORACIC_INCISION_VIDEO_V7) is VideoStream, "Seventh thoracic incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.THORACIC_INCISION_VIDEO_V8), "Eighth thoracic incision OGV is missing")
	expect(load(app.THORACIC_INCISION_VIDEO_V8) is VideoStream, "Eighth thoracic incision OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.THORACIC_INCISION_VIDEO_V9), "Ninth thoracic incision OGV is missing")
	expect(load(app.THORACIC_INCISION_VIDEO_V9) is VideoStream, "Ninth thoracic incision OGV did not load as a VideoStream")
	var abdominal_video_pool: Array = app.INCISION_VIDEO_POOLS.abdominal
	expect(abdominal_video_pool.size() == 7, "Abdominal incision pool does not contain seven unique videos")
	var first_incision_video: String = app.incision_video_path("incise_none", "general_abdominal", false)
	var second_incision_video: String = app.incision_video_path("incise_none", "vascular", false)
	expect(first_incision_video in abdominal_video_pool and second_incision_video in abdominal_video_pool, "Abdominal incision pool returned an unknown video")
	expect(first_incision_video != second_incision_video, "Abdominal incision pool repeated the previous video")
	var pelvic_video_pool: Array = app.INCISION_VIDEO_POOLS.pelvic
	expect(pelvic_video_pool.size() == 4, "Pelvic incision pool does not contain four unique videos")
	var first_pelvic_video: String = app.incision_video_path("incise_epidural", "female_pelvic", false)
	var second_pelvic_video: String = app.incision_video_path("incise_epidural", "female_pelvic", false)
	expect(first_pelvic_video in pelvic_video_pool and second_pelvic_video in pelvic_video_pool, "Pelvic incision pool returned an unknown video")
	expect(first_pelvic_video != second_pelvic_video and first_pelvic_video not in abdominal_video_pool and second_pelvic_video not in abdominal_video_pool, "Pelvic incision repeated or leaked into the abdominal pool")
	expect(app.incision_video_path("incise_local", "urologic", false) in abdominal_video_pool, "Awake urologic incision did not select its video")
	expect(app.incision_video_path("incise_general", "general_abdominal", true) in abdominal_video_pool, "General anesthesia did not select a silent incision video")
	var breast_video_pool: Array = app.INCISION_VIDEO_POOLS.breast
	expect(breast_video_pool.size() == 8, "Breast incision pool does not contain eight unique videos")
	var first_breast_video: String = app.incision_video_path("incise_none", "breast", false)
	var second_breast_video: String = app.incision_video_path("incise_none", "breast", false)
	expect(first_breast_video in breast_video_pool and second_breast_video in breast_video_pool, "Breast incision pool returned an unknown video")
	expect(first_breast_video != second_breast_video, "Breast incision pool repeated the previous video")
	var thoracic_video_pool: Array = app.INCISION_VIDEO_POOLS.thoracic
	expect(thoracic_video_pool.size() == 9, "Thoracic incision pool does not contain nine unique videos")
	var first_thoracic_video: String = app.incision_video_path("incise_none", "thoracic", false)
	var second_thoracic_video: String = app.incision_video_path("incise_general", "cardiac", true)
	expect(first_thoracic_video in thoracic_video_pool and second_thoracic_video in thoracic_video_pool, "Thoracic or cardiac surgery returned an unknown video")
	expect(first_thoracic_video != second_thoracic_video, "Shared thoracic/cardiac pool repeated the previous video")
	expect(app.incision_video_path("incise_none", "unknown", false).is_empty(), "Unknown surgery group selected an incision video")
	var awake_preparation := MockPreparation.new()
	awake_preparation.flags.append("no_anesthesia_confirmed")
	expect(not app.incision_video_should_mute(awake_preparation), "No-anesthesia incision animation was muted")
	var anesthetized_preparation := MockPreparation.new()
	anesthetized_preparation.flags.append("anesthetized")
	expect(app.incision_video_should_mute(anesthetized_preparation), "Anesthetized incision animation retained live audio")
	expect(ResourceLoader.exists(app.CHANGE_SCRUBS_VIDEO), "Change-scrubs transition OGV is missing")
	expect(load(app.CHANGE_SCRUBS_VIDEO) is VideoStream, "Change-scrubs transition OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.SCRUB_HANDS_VIDEO), "Scrub-hands transition OGV is missing")
	expect(load(app.SCRUB_HANDS_VIDEO) is VideoStream, "Scrub-hands transition OGV did not load as a VideoStream")
	expect(ResourceLoader.exists(app.ENTER_OPERATING_ROOM_VIDEO), "Enter-room transition OGV is missing")
	expect(load(app.ENTER_OPERATING_ROOM_VIDEO) is VideoStream, "Enter-room transition OGV did not load as a VideoStream")
	var change_scrubs_video: Dictionary = app.preop_transition_video_for("change_scrubs")
	expect(change_scrubs_video.get("path", "") == app.CHANGE_SCRUBS_VIDEO and is_equal_approx(float(change_scrubs_video.get("speed", 0.0)), 2.0), "Change-scrubs action did not resolve its 2x transition video")
	var scrub_hands_video: Dictionary = app.preop_transition_video_for("scrub_hands")
	expect(scrub_hands_video.get("path", "") == app.SCRUB_HANDS_VIDEO and is_equal_approx(float(scrub_hands_video.get("speed", 0.0)), 2.0), "Scrub-hands action did not resolve its 2x transition video")
	var enter_room_video: Dictionary = app.preop_transition_video_for("enter_room")
	expect(enter_room_video.get("path", "") == app.ENTER_OPERATING_ROOM_VIDEO and is_equal_approx(float(enter_room_video.get("speed", 0.0)), 2.0), "Enter-room action did not resolve its 2x transition video")
	expect(PreopView.background_id_for({"kind": "changing", "background_id": "changing"}, ["changed"], false, "") == "scrub_area", "Changed preop state did not resolve to the dedicated scrub-area background")
	app.show_preop_transition_video(change_scrubs_video, app.show_map)
	await process_frame
	var transition_player: VideoStreamPlayer = app.page.get_node_or_null("PreopTransitionVideoPlayer")
	expect(app.screen == "preop_transition_video" and transition_player != null and transition_player.is_playing(), "Preop transition video did not open and begin playback")
	expect(transition_player != null and is_equal_approx(transition_player.speed_scale, 2.0) and transition_player.volume_db <= -79.0, "Preop transition video did not play silently at 2x speed")
	expect(transition_player != null and transition_player.position == Vector2(264, 192) and transition_player.size == Vector2(752, 416), "Preop transition video was not centered at its native borderless presentation size")
	expect(app.page.get_node_or_null("PreopTransitionVideoFrame") == null, "One-second preop transition unexpectedly added a decorative frame")
	expect(app.page.get_node_or_null("PreopTransitionVideoSkip") == null, "One-second preop transition unexpectedly added a skip control")
	await create_timer(1.4).timeout
	expect(app.screen == "map" and not app.preop_transition_video_next.is_valid(), "Preop transition video did not continue automatically or retained a stale callback")
	app.show_surgery_video(app.ABDOMINAL_INCISION_VIDEO, app.show_map)
	await process_frame
	var player: VideoStreamPlayer = app.page.get_node_or_null("SurgeryVideoPlayer")
	expect(app.screen == "surgery_video" and player != null, "Surgery video overlay did not open")
	expect(player != null and player.is_playing(), "Surgery video did not begin playback")
	expect(player != null and is_equal_approx(player.speed_scale, 1.25), "Surgery video did not play at 1.25x speed")
	expect(player != null and is_equal_approx(player.volume_db, 0.0), "No-anesthesia surgery video did not preserve its audio")
	expect(app.page.get_node_or_null("SurgeryVideoSkip") != null, "Surgery video has no skip control")
	app.complete_surgery_video()
	await process_frame
	expect(app.screen == "map", "Surgery video did not continue to the requested view")
	app.show_surgery_video(app.ABDOMINAL_INCISION_VIDEO, app.show_map, true)
	await process_frame
	var muted_player: VideoStreamPlayer = app.page.get_node_or_null("SurgeryVideoPlayer")
	expect(muted_player != null and muted_player.volume_db <= -79.0, "Anesthetized surgery video was not muted")
	# The 6.04-second source takes about 4.83 seconds at the configured 1.25x.
	await create_timer(5.3).timeout
	expect(app.screen == "map", "Surgery video did not continue automatically after playback")
	expect(not app.surgery_video_next.is_valid(), "Finished video retained a stale continuation callback")
	print("Surgery video checks: %s, failures: %s" % [checks, failures])
	quit(1 if failures > 0 else 0)
